version: "3.6"

services:
  author:
    depends_on:
      - publish
    build: .
    command: python3 /aem/scripts/startup.py author
    volumes:
      - ./author/logs:/aem/crx-quickstart/logs
    ports:
      - 4502:4502
      - 5502:5502
  publish:
    build: .
    command: python3 /aem/scripts/startup.py publish
    volumes:
      - ./publish/logs:/aem/crx-quickstart/logs
    ports:
      - 4503:4503
  app:
    depends_on:
      - author
      - publish
    build: ./app
    entrypoint: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app/src/app.py:/src/app.py
      - ./author/packages:/src/author/packages
      - ./publish/packages:/src/publish/packages
    ports:
      - 8000:8000
  # sonar:
  #   image: sonarqube:community
  #   depends_on:
  #     - postgres
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   volumes:
  #     - ./sonarqube/data:/opt/sonarqube/data
  #     - ./sonarqube/logs:/opt/sonarqube/logs
  #     - ./sonarqube/extensions:/opt/sonarqube/extensions
  #   ports:
  #     - 9000:9000
  # postgres:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #   volumes:
  #     - ./sonarqube/postgres/postgresql:/var/lib/postgresql
  #     - ./sonarqube/postgres/data:/var/lib/postgresql/data
      